#!/bin/sh
set -e
set -x

if [ "`uname`" = "Darwin" ]; then
	# Fix sed error on Mountain Lion: "illegal byte sequence"
	export LC_ALL=C
fi

if [ -z "$PEPPER_SRCDIR" ]; then
	PEPPER_SRCDIR=".."
fi

# Generate the man page
(cd $PEPPER_SRCDIR/docs; make pepper.1.html &> /dev/null; cat pepper.1.html) > src/documentation/manpage.mdwn
sed -i -e 's/jonas\.gehring/$FORENAME.$SURENAME/' src/documentation/manpage.mdwn
sed -i -e 's/<html><head>.*<div class="refnamediv"/<div class="refnamediv"/' src/documentation/manpage.mdwn
sed -i -e 's/<\/body>//' src/documentation/manpage.mdwn

# Generate examples
if [ "$1" = "--full" ]; then
	(cd src/gallery; ../../scripts/make_examples.sh ../../../src/pepper)
fi

ikiwiki --setup setup

# Copy static files from pepper's source code directory
cp "$PEPPER_SRCDIR/README" pub/documentation/
rm -rf pub/documentation/api
(cd $PEPPER_SRCDIR; make luadoc)
cp -r "$PEPPER_SRCDIR/luadoc" pub/documentation/api
cp "$PEPPER_SRCDIR/ChangeLog" pub/download/

# Fix pages
sed -i -e 's/<title>pepper</<title>pepper - Repository statistics and report tool</' pub/index.html
